---
- name: Ensure flatpak ppa
  apt_repository:
    repo: ppa:alexlarsson/flatpak

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: safe

- name: Ensure packages (this might take a looooong time)
  apt:
    name:
      - flatpak
      - gnome-software-plugin-flatpak
      - curl
      - openssh-server
      - gparted
      - byobu
      - snapd
      - zsh
      - wget
      - dnsutils
      - git
      - sudo
      - htop
      - bmon
      - vim
      - nano
      - inxi
      - txt2html
      - wkhtmltopdf
    state: latest
    install_recommends: yes

- name: Add the flathub flatpak repository remote to the system installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Register flatpak list
  set_fact:
    flatpak_list:
     - org.chromium.Chromium

- name: Install flatpak packages
  flatpak:
    remote: flathub
    name: "{{ item }}"
    state: present
  with_items: "{{ flatpak_list }}"