---
- name: Ensure packages
  apt:
    name:
      - gettext
      - sassc
      - libglib2.0-dev-bin
      - gnome-tweaks
      - gnome-shell-extensions
    state: latest
  when: not uninstall | bool

- name: Determine existing users
  shell: 'cat /etc/passwd | grep /bin/bash | grep -v root | grep -v guest | cut -d: -f1'
  changed_when: false 
  register: ubuntu_users

- name: Ensure git repos gnome shell extensions
  ansible.builtin.git:
    repo: "{{ item.url }}"
    dest: "/srv/widgets/{{ item.folder }}"
    clone: yes
    update: yes
    force: yes
    version: "{{ item.version }}"
  with_items: "{{ config_widgets }}"

- name: Make gnome shell extensions
  shell: "{{ item.install }}"
  args:
    chdir: "/srv/widgets/{{ item.folder }}"
  become: yes
  changed_when: false
  with_items: "{{ config_widgets }}"
  when: item.install is defined

- name: Ensure gnome shell extensions
  copy:
      src: "/srv/widgets/{{ item.folder }}/{{ item.ensure }}"
      dest: /usr/share/gnome-shell/extensions
      owner: root
      group: root
  with_items: "{{ config_widgets }}"

- name: Ensure user widget state
  shell: "gnome-extensions enable extensions@abteil.org"
  become_user: "{{ item }}"
  changed_when: false
  with_items: "{{ ubuntu_users.stdout_lines }}"