---
- name: Ensure packages
  apt:
    name:
      - gettext
      - sassc
      - libglib2.0-dev-bin
      - gnome-tweaks
      - gnome-shell-extensions
      - make
    state: latest
  when: not uninstall | bool

- name: Getting CPU information
  shell: cat /proc/cpuinfo | grep "model name"
  register: cpu_info
  changed_when: false

- name: Ensure git repos gnome shell extensions
  ansible.builtin.git:
    repo: "{{ item.url }}"
    dest: "/srv/widgets/{{ item.folder }}"
    clone: yes
    update: yes
    force: yes
    version: "{{ item.version }}"
    refspec: '+refs/tags/*:refs/tags/*'
  with_items: "{{ config_widgets }}"
  ignore_errors: yes
  notify:
    - make extensions