---
- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart ufw
  service:
    name: ufw
    state: restarted

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: notification start apt
  shell: DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/`id -u {{ item }}`/bus notify-send 'UPDATE STARTED' 'Do not shut down PC - update in progess.' -i important 
  become_user: "{{ item }}"
  with_items: "{{ ubuntu_users_reg.stdout_lines }}"
  ignore_errors: yes

- name: update apt
  apt:
    update_cache: yes
  ignore_errors: yes

- name: upgrade apt
  apt:
    name: "*"
    state: latest
  ignore_errors: yes

- name: dist-upgrade
  apt:
    upgrade: dist
  ignore_errors: yes

- name: autoremove apt
  apt:
    autoremove: yes

- name: notification stop apt
  shell: DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/`id -u {{ item }}`/bus notify-send 'UPDATE FINISHED' 'Update progess finished.' -i emblem-default
  become_user: "{{ item }}"
  with_items: "{{ ubuntu_users_reg.stdout_lines }}"
  ignore_errors: yes