---
- name: Check if backscrub binary is present
  stat: 
    path: "{{ backscrub_binary }}"
  register: check_if_binary_present
  changed_when: not check_if_binary_present.stat.exists
  notify:
    - cleanup backscrub tmpdir
    - ensure backscrub tmpdir
    - make backscrub
    - ensure backscrub binary

- name: Getting CPU information
  shell: cat /proc/cpuinfo | grep processor | wc -l
  register: cpu_info
  changed_when: false

- name: find model
  find:
    paths: "{{ backscrub_folders.backscrubrepo }}/models"
    recurse: no
    pattern: "selfiesegmentation*.tflite"
  register: fakecam_models

- name: Ensure scripts
  template:
    src: "{{ item.entry }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  loop:
    - { entry: "fakecam.j2", dest: "/usr/local/bin/fakecam" }
    - { entry: "rotatecam.j2", dest: "/usr/local/bin/rotatecam" }

- name: Ensure wallpaper
  copy:
    src: "blackboard.jpg"
    dest: "{{ backscrub_background }}"
    mode: 0755