#!/usr/bin/env ansible-playbook

- hosts: localhost
  collections:
    - community.general
    - community.crypto

- name: Import local configs
  hosts: localhost
  become: yes
  tags:
    - always
  tasks:
    - name: Include vars file if present
      include_vars: "{{ item }}"
      with_first_found:
        - files:
            - vars.yml
            - /root/.config/vars_sysconfig.yml
          skip: true

- name: Ensure widgets
  hosts: localhost
  become: yes
  tags:
    - never
    - widgets
    - bigsetup
  roles:
    - widgets

- name: Maintenance script
  hosts: localhost
  become: yes
  tags:
    - base
    - deploy
    - setup
    - bigsetup
  roles:
    - base

- name: Deploy script
  hosts: localhost
  become: yes
  tags:
    - deploy
  roles:
    - deploy


- name: Initial setup and update routine
  hosts: localhost
  become: yes
  tags:
    - never
    - setup
    - bigsetup
    - downgrade
  roles:
    - setup
    - security

- name: Ensure unattended-upgrades
  hosts: localhost
  become: yes
  tags:
    - never
    - deploy
    - unattended-upgrades
    - setup
    - bigsetup
  roles:
    - ubuntu-unattended-upgrades

- name: Install Docker
  hosts: localhost
  become: yes
  tags:
    - never
    - docker
    - bigsetup
    - install_pihole
    - install_webcam
  roles:
    - docker

- name: Install themes
  hosts: localhost
  become: yes
  tags:
    - never
    - themes
  roles:
    - themes

- name: Install fonts
  hosts: localhost
  become: yes
  tags:
    - never
    - fonts
    - setup
    - bigsetup
  roles:
    - fonts

- name: Install mbz tool
  hosts: localhost
  become: yes
  tags: 
    - never
    - mbz
  roles:
    - mbz

- name: Deploy fritzbox tools
  hosts: localhost
  become: yes
  tags:
    - never
    - fritzbox
  roles:
    - fritzbox

- name: Install Webcam Tools
  hosts: localhost
  become: yes
  tags:
    - never
    - webcam
    - install_webcam
  roles:
    - webcam

- name: Install pihole
  hosts: localhost
  become: yes
  tags: 
    - never
    - pihole
    - install_pihole
    - uninstall_pihole
  roles:
    - pihole
