---
- debug: var=ansible_facts

- name: Repair system
  hosts: localhost
  become: yes
  tags: [ 'never', 'repair' ]
  roles:
    - repair

- name: Maintenance script
  hosts: localhost
  become: yes
  tags:
    - base
  roles:
    - base

