---
- name: Repair system
  hosts: all
  become: yes
  tags: [ 'never', 'repair' ]
  roles:
    - repair

- name: Maintenance script
  hosts: all
  become: yes
  tags:
    - base
  roles:
    - base

