---
- hosts: localhost
  collections:
    - community.general

- name: Import local configs
  hosts: localhost
  become: yes
  tags:
    - always
  tasks:
    - name: Include vars file if present
      include_vars: "{{ item }}"
      with_first_found:
        - files:
            - vars.yml
          skip: true

- name: Repair system
  hosts: localhost
  become: yes
  tags: 
    - never
    - repair
  roles:
    - repair

- name: Maintenance script
  hosts: localhost
  become: yes
  tags:
    - base
  roles:
    - base

- name: Packages to deploy as installation image
  hosts: localhost
  become: yes
  tags:
    - never
    - deploy
  roles:
    - base
    - deploy

- name: Initial setup and update routine
  hosts: localhost
  become: yes
  tags:
    - never
    - setup
  roles:
    - repair
    - base
    - setup
    - mbz
    - security

- name: Install Docker
  hosts: localhost
  become: yes
  tags:
    - never
    - docker
  roles:
    - docker

- name: Install Webcam Tools
  hosts: localhost
  become: yes
  tags:
    - never
    - webcam
  roles:
    - repair
    - docker
    - webcam

- name: Install mbz tool
  hosts: localhost
  become: yes
  tags: 
    - never
    - mbz
  roles:
    - mbz

- name: Deploy fritzbox tools
  hosts: localhost
  become: yes
  tags:
    - never
    - fritzbox
  roles:
    - fritzbox
