---
- name: Repair system
  hosts: localhost
  become: yes
  tags:
    - repair
  roles:
    - repair

- name: Maintenance script
  hosts: localhost
  become: yes
  tags:
    - base
  roles:
    - base

