---
- name: Initial setup and update routine
  hosts: localhost
  become: yes
  tags:
    - setup
  roles:
    - repair
    - base
    - setup
    - security

- name: Install docker
  hosts: localhost
  become: yes
  tags: [ 'never', 'docker' ]
  roles:
    - docker
