---
removebg_backend: "cpu"
gpu_enabled: "{{ False if removebg_backend=='cpu' else True }}"
removebg_docker_image: "docker.io/anodev/carvekit"
removebg_docker_image_tag: "latest-{{ 'cuda' if gpu_enabled|bool else 'cpu' }}"

removebg_bin: "/usr/local/bin/removebg"
removebg_api_key: "localaccess"

removebg_dir: "/srv/removebg"

use_poman: True

compose_bin: "{{ '/usr/local/bin/podman-compose' if use_poman else '/usr/local/bin/docker-compose' }}"
container_bin: "{{ '/usr/local/bin/podman' if use_poman else '/usr/local/bin/docker' }}"

##building env
npm_image: "node"
npm_tag: "14.18.1"

rembg_cli_repo: "https://github.com/remove-bg/remove-bg-cli.git"
rembg_cli_repo_version: "main"
rembg_cli_repo_dir: "{{ removebg_dir }}/build"
build_docker_name: "rembgbuild"