---
- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart ufw
  service:
    name: ufw
    state: restarted
  ignore_errors: yes

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
  ignore_errors: yes

########### ENSURING UPDATE EXECUTABLE WITH SETUID ###########

- name: ensuring shc
  apt:
    name:
      - shc
      - gcc
    state: latest
    install_recommends: yes
  ignore_errors: yes
  become: yes

- name: ensuring update exe
  shell: "/usr/bin/shc -S -f {{ item.name }}; chmod u+s {{ item.name }}.x"
  args:
    chdir: "{{ item.root }}"
  become: yes
  loop: "{{ shc_binaries }}"
  ignore_errors: yes

##############################################################

- name: notification start apt
  shell: DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/`id -u {{ item }}`/bus notify-send 'UPDATE STARTED' 'Do not shut down PC - update in progess.' -i important 
  become_user: "{{ item }}"
  with_items: "{{ ubuntu_users_reg.stdout_lines }}"
  ignore_errors: yes

- name: update apt
  apt:
    update_cache: yes
  register: apt_return
  until: '(apt_return.rc | default(0) == 0) and ("Failed" not in apt_return.msg | default(""))'
  retries: 3
  delay: 30

- name: autoremove apt
  apt:
    autoremove: yes
  register: apt_return
  until: '(apt_return.rc | default(0) == 0) and ("Failed" not in apt_return.msg | default(""))'
  retries: 3
  delay: 30

- name: upgrade apt
  apt:
    name: "*"
    state: latest
  register: apt_return
  until: '(apt_return.rc | default(0) == 0) and ("Failed" not in apt_return.msg | default(""))'
  retries: 3
  delay: 30

- name: dist-upgrade
  apt:
    upgrade: dist
  register: apt_return
  until: '(apt_return.rc | default(0) == 0) and ("Failed" not in apt_return.msg | default(""))'
  retries: 3
  delay: 30

- name: autoremove flatpaks
  shell: flatpak uninstall --unused -y
  become: yes
  ignore_errors: yes

- name: notification stop apt
  shell: DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/`id -u {{ item }}`/bus notify-send 'UPDATE FINISHED' 'Update progess finished.' -i emblem-default
  become_user: "{{ item }}"
  with_items: "{{ ubuntu_users_reg.stdout_lines }}"
  ignore_errors: yes