---
- name: Ensure darktable ppa absent
  apt_repository:
    repo: ppa:pmjdebruijn/darktable-release
    
  when: ansible_facts['lsb']['id'] == "Ubuntu" and ansible_facts['lsb']['major_release']| int < 20

- name: Ensure freecad ppa
  apt_repository:
    repo: ppa:freecad-maintainers/freecad-stable
    state: absent
  when: ansible_facts['lsb']['id'] == "Ubuntu" and ansible_facts['lsb']['major_release']| int < 20

- name: Ensure cubic ppa
  apt_repository:
    repo: ppa:cubic-wizard/release

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: safe

- name: Ensure packages
  apt:
    name:
      - texstudio
      - texlive-full
      - texlive-extra-utils
      - texlive-latex-recommended
      - kdenlive
      - libmp3lame-dev
      - libfaac-dev
      - libfaad-dev
      - libxvidcore4
      - swh-plugins
      - cubic
      - scribus
      - scribus-doc
      - scribus-template
      - icc-profiles
      - liblocale-codes-perl
      - gscan2pdf
      - octave
      - octave-doc
      - gnuplot 
      - virtualbox
      - virtualbox-qt
      - virtualbox-dkms
      - virtualbox-guest-additions-iso
    state: latest
    install_recommends: yes

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Install flatpak packages
  flatpak:
    remote: flathub
    name: "{{ item }}"
    state: present
  with_items:
     - org.zotero.Zotero
     - com.github.tchx84.Flatseal
     - io.github.Soundux
     - org.darktable.Darktable
     - org.freecadweb.FreeCAD
