---
# settings
## ensure teamviewer deamon is disabled at every startup
disable_teamviewer: true
## upgrade apt with basic role
config_perform_apt_upgrade: false

# update systemctl command

shutdown_after_update_systemctl_cmd: "poweroff"

# repo details
config_repo_name: "tna76874/hdhweg-ubuntu"
config_repo_url: "https://github.com/{{ config_repo_name }}.git"
config_repo_branch: "master"
config_repo_setup: "https://raw.githubusercontent.com/{{ config_repo_name }}/{{ config_repo_branch }}/setup.sh"
# repo folder
config_repo_folder: "/root/hdhweg-ubuntu"

# cron options
config_autopull_repo: true
config_autopull_repo_time: "10m"
config_autopull_repo_file: "autoupdate"

config_autorun_base: true
config_autorun_base_time: "15m"
config_autorun_base_file: "hdhweg_maintenance"

# ensure git repo at playbook run
config_ensure_repo: "{{ config_autopull_repo }}"

# remove playbook from system
config_uninstall_playbook: false

# disable tracker to reduce system load
config_disable_tracker: true

# extensions states

config_extension_states:
    - {ext: "extensions@abteil.org", state: "enable"}
    - {ext: "caffeine@patapon.info", state: "enable"}

# restic config
config_restic_path: '/snap/bin/restic'

config_restic_prune_policy: '--keep-daily 7 --keep-weekly 5 --keep-monthly 12 --keep-yearly 1'

# tracker disable commands
tracker_disable_commands:
  tracker2:
    cmd: "systemctl --user mask tracker-store.service tracker-miner-fs.service tracker-miner-rss.service tracker-extract.service tracker-miner-apps.service tracker-writeback.service"
    reset: "yes j | tracker reset --hard"
  tracker3:
    cmd: "systemctl --user mask tracker-extract-3.service tracker-miner-fs-3.service tracker-miner-rss-3.service tracker-writeback-3.service tracker-xdg-portal-3.service tracker-miner-fs-control-3.service"
    reset: "yes j | tracker3 reset -s -r"

tracker_disable:
  cmd: "{{ tracker_disable_commands.tracker3.cmd if ansible_facts['lsb']['major_release']| int >= 22 else tracker_disable_commands.tracker2.cmd }}"
  reset: "{{ tracker_disable_commands.tracker3.reset if ansible_facts['lsb']['major_release']| int >= 22 else tracker_disable_commands.tracker2.reset }}"

# support details !!!
config_show_support_in_favorites: false

gotify_notify_dest:
  - {host: "push.hilberg.eu", key: "AGYHlNHiACJ9TCo"}

rustdesk_config:
  host: 'rd.hilberg.eu'
  key: 'gGhfhdygWBEma9gpErFe2rmcibBaFLEoSvSPYhlqY+g='

config_tunnel_ssh_keys: "https://github.com/tna76874.keys"

teamviewer_enabled: False

# shc binaries
recompile_shc: False
shc_binaries:
  - { file: "open_support_ssh.j2", root: "/usr/local/bin/", name: "open_support_ssh", owner: "root", mode: "0750", binmode: "4750" }
  - { file: "update_gui.j2", root: "/usr/local/bin/", name: "update_gui", owner: "root", mode: "0755", binmode: "4750" }
  - { file: "open_ap.j2", root: "/usr/local/bin/", name: "open_ap", owner: "root", mode: "0755", binmode: "4750" }
  - { file: "start_teamviewer.j2", root: "/usr/local/bin/", name: "start_teamviewer", owner: "root", mode: "0755", binmode: "4750" }