---
# settings
## ensure teamviewer deamon is disabled at every startup
disable_teamviewer: true
## upgrade apt with basic role
config_perform_apt_upgrade: false

# repo details
config_repo_name: "tna76874/hdhweg-ubuntu"
config_repo_url: "https://github.com/{{ config_repo_name }}.git"
config_repo_branch: "master"
config_repo_setup: "https://raw.githubusercontent.com/{{ config_repo_name }}/{{ config_repo_branch }}/setup.sh"
# repo folder
config_repo_folder: "/root/hdhweg-ubuntu"

# cron options
config_autopull_repo: true
config_autopull_repo_time: "10m"
config_autopull_repo_file: "autoupdate"

config_autorun_base: true
config_autorun_base_time: "15m"
config_autorun_base_file: "hdhweg_maintenance"

# ensure git repo at playbook run
config_ensure_repo: "{{ config_autopull_repo }}"

# remove playbook from system
config_uninstall_playbook: false

# extensions states

config_extension_states:
    - {ext: "extensions@abteil.org", state: "enable"}
    - {ext: "caffeine@patapon.info", state: "enable"}