---
- name: Determine existing users
  shell: 'cat /etc/passwd | grep /bin/bash | grep -v root | grep -v guest | cut -d: -f1'
  changed_when: false 
  register: ubuntu_users

- name: Ensure obs-studio ppa
  apt_repository:
    repo: ppa:obsproject/obs-studio
    state: present
    filename: obsstudio

- name: Ensure packages
  apt:
    name:
      - obs-studio
      - cmake
      - qtbase5-dev
      - obs-plugins
      - libqt
      - libobs0
      - libobs-dev
    state: latest
    install_recommends: yes
  ignore_errors: yes

- name: Ensure obs-studio repo
  ansible.builtin.git:
    repo: 'https://github.com/obsproject/obs-studio.git'
    dest: /srv/webcam/obs-studio
    force: yes

- name: Ensure v4l2loopback repo
  ansible.builtin.git:
    repo: 'https://github.com/umlaeute/v4l2loopback.git'
    dest: /srv/webcam/v4l2loopback
    force: yes

- name: Ensure akvcam repo
  ansible.builtin.git:
    repo: 'https://github.com/webcamoid/akvcam.git'
    dest: /srv/webcam/akvcam
    force: yes

- name: Ensure obs-v4l2 repo
  ansible.builtin.git:
    repo: 'https://github.com/CatxFish/obs-v4l2sink'
    dest: /srv/webcam/obs-v4l2
    force: yes

- name: Ensure install_webcam.sh
  template:
    src: "install_webcam.sh"
    dest: "/srv/webcam/install_webcam.sh"
    owner: root
    group: root
    mode: 0766

- name: Run install script for webcam tools
  shell: "/srv/webcam/install_webcam.sh"
  become: yes

- name: Ensure obs v4l2sink plugin directory
  ansible.builtin.file:
    path: "/home/{{ item }}/.config/obs-studio/plugins/v4l2sink/bin/64bit/"
    state: directory
  become_user: "{{ item }}"
  with_items: "{{ ubuntu_users.stdout_lines }}"

- name: Ensure obs v4l2sink.so softlink
  ansible.builtin.file:
    src: /usr/lib/obs-plugins/v4l2sink.so
    dest: "/home/{{ item }}/.config/obs-studio/plugins/v4l2sink/bin/64bit/v4l2sink.so"
    state: link
  become_user: "{{ item }}"
  with_items: "{{ ubuntu_users.stdout_lines }}"

- name: Ensure droidcam desktop entry
  template:
    src: droidcam.desktop
    dest: "/usr/share/applications/droidcam.desktop"
    mode: 0644

- name: Ensure droidcam logo
  copy:
    src: droidcam.png
    dest: "/usr/share/icons/droidcam.png"
    mode: 0644


