- name: Ensure pip packages
  pip:
    name: "{{ item.name }}"
    executable: "{{ item.executable }}"
    state: "{{ item.state }}"
  become: true
  loop:
    - { name: "podman-compose", executable: "pip3", state: "latest"}
  ignore_errors: yes