---
- name: Ensure autopull is disabled
  cron:
    name: "running ansible playbook at reboot"
    cron_file: "autoupdate"
    special_time: reboot
    job: "(sleep 10m; sudo git -C {{ config_repo_folder }} pull > /dev/null 2>&1)&"
    user: root
    state: absent
