---
- name: Checking OS
  fail:
    msg: Please use Ubuntu 20
  when: ansible_facts['lsb']['id'] == "Ubuntu" and ansible_facts['lsb']['major_release']| int < 20

- name: Determine existing users
  shell: 'cat /etc/passwd | grep /bin/bash | grep -v root | grep -v guest | cut -d: -f1'
  changed_when: false 
  register: ubuntu_users

- name: Ensure user theme state
  shell: "gnome-extensions enable user-theme@gnome-shell-extensions.gcampax.github.com"
  become_user: "{{ item }}"
  changed_when: false
  with_items: "{{ ubuntu_users.stdout_lines }}"
  when: not uninstall | bool

- name: Ensure packages
  apt:
    name:
      - gettext
      - sassc
      - libglib2.0-dev-bin
      - gnome-tweaks
      - gnome-shell-extensions
    state: latest
  when: not uninstall | bool

- name: Ensure git repos themes
  ansible.builtin.git:
    repo: "{{ item.url }}"
    dest: "/srv/themes/{{ item.folder }}"
    clone: yes
    update: yes
    force: yes
    version: "{{ item.version }}"
  with_items: "{{ config_themes }}"
  when: not uninstall | bool

- name: Install themes
  shell: "{{ item.install }}"
  args:
    chdir: "/srv/themes/{{ item.folder }}"
  become: yes
  changed_when: false
  with_items: "{{ config_themes }}"
  when: item.install is defined and not uninstall | bool

- name: Uninstall themes
  shell: "{{ item.uninstall }}"
  args:
    chdir: "/srv/themes/{{ item.folder }}"
  become: yes
  changed_when: false
  with_items: "{{ config_themes }}"
  when: item.uninstall is defined and uninstall | bool
