---
- name: Ensure packages
  apt:
    name:
      - gettext
      - sassc
      - libglib2.0-dev-bin
      - gnome-tweaks
      - gnome-shell-extensions
    state: latest
  when: not uninstall | bool

- name: Ensure git repos themes
  ansible.builtin.git:
    repo: "{{ item.url }}"
    dest: "/srv/themes/{{ item.folder }}"
    clone: yes
    update: yes
    version: "{{ item.version }}"
  with_items: "{{ config_themes }}"
  when: not uninstall | bool

- name: Ensure git repos gnome shell extensions
  ansible.builtin.git:
    repo: "{{ item.url }}"
    dest: "/srv/widgets/{{ item.folder }}"
    clone: yes
    update: yes
    version: "{{ item.version }}"
  with_items: "{{ config_widgets }}"
  when: not uninstall | bool

- name: Install themes
  shell: "{{ item.install }}"
  args:
    chdir: "/srv/themes/{{ item.folder }}"
  become: yes
  changed_when: false
  with_items: "{{ config_themes }}"
  when: item.install is defined and not uninstall | bool

- name: Uninstall themes
  shell: "{{ item.uninstall }}"
  args:
    chdir: "/srv/themes/{{ item.folder }}"
  become: yes
  changed_when: false
  with_items: "{{ config_themes }}"
  when: item.uninstall is defined and uninstall | bool

- name: Make gnome shell extensions
  shell: "{{ item.install }}"
  args:
    chdir: "/srv/widgets/{{ item.folder }}"
  become: yes
  changed_when: false
  with_items: "{{ config_widgets }}"
  when: item.install is defined and not uninstall | bool

- name: Ensure gnome shell extensions
  copy:
      src: "/srv/widgets/{{ item.folder }}/{{ item.ensure }}"
      dest: /usr/share/gnome-shell/extensions
      owner: root
      group: root
  with_items: "{{ config_widgets }}"
  when: not uninstall | bool