---
# custom wifi drivers

rtw89_repo_url: { url: "https://github.com/lwfinger/rtw89.git", version: 'main' }
rtw89_repo_dir: "/srv/rtw89"
ensure_rtw89_module: false

# extended software package
config_extended_software: false

# downgrade custom package

config_downgrade: false

# generate config file

config_generate_config_file: false

# Software details

config_apt_ppa_list_1:
  # Present
  - { ppa: "ppa:marko-preuss/hibiscus", state: "present"}
  - { ppa: "ppa:ubuntu-mozilla-security/ppa", state: "present"}
  - { ppa: "ppa:unit193/encryption", state: "present"}
  - { ppa: "ppa:alexlarsson/flatpak", state: "present"}
  # Absent
  - { ppa: "ppa:nextcloud-devs/client", state: "absent"}
  - { ppa: "ppa:andreasbutti/xournalpp-master", state: "absent"}
  - { ppa: "ppa:apandada1/xournalpp-stable", state: "absent"}
  - { ppa: "ppa:smathot/cogscinl", state: "absent"}

config_apt_ppa_list_2:
  - { ppa: "ppa:tomtomtom/woeusb", state: "present"}
  - { ppa: "ppa:cubic-wizard/release", state: "present"}

config_apt_list_1:
  - curl
  - openssh-server
  - gparted
  - byobu
  - snapd
  - zsh
  - wget
  - dnsutils
  - git
  - git-gui
  - sudo
  - htop
  - powertop
  - bmon
  - vim
  - nano
  - pwgen
  - nautilus
  - vlc
  - libxvidcore4
  - vlc-plugin-fluidsynth
  - vlc-plugin-jack
  - libdvdnav4
  - gstreamer1.0-plugins-bad
  - gstreamer1.0-plugins-ugly
  - ubuntu-restricted-extras
  - software-properties-common
  - audacious
  - audacious-plugins
  - poppler-utils
  - ocrmypdf
  - tesseract-ocr
  - tesseract-ocr-deu
  - libfaac0
  - rclone
  - restic
  - clamav
  - clamav-freshclam
  - clamtk
  - gcc
  - wipe
  - unzip
  - p7zip
  - p7zip-full
  - p7zip-rar
  - tar
  - htop
  - screen
  - ncdu
  - dos2unix
  - speedtest-cli
  - net-tools
  - traceroute
  - imagemagick
  - gnuplot
  - gnuplot-x11
  - gnuplot-doc
  - recoll
  - poppler-utils
  - gnome-shell-extensions
  - gnome-clocks
  - mupdf-tools
  - pdfposter
  - pdfsam
  - img2pdf
  - inxi
  - txt2html
  - wkhtmltopdf
  - qtqr
  - macchanger
  - youtube-dl
  - teamviewer
  - autossh
  - zbar-tools
  - texlive-extra-utils
  - ca-certificates
  - hplip
  - libreoffice-common
  - python3
  - python3-pip
  - veracrypt
  - simple-scan
  - nautilus-wipe
  - usb-creator-gtk
  - gnome-tweaks
  - gnome-shell-extensions
  - gettext
  - sassc
  - libglib2.0-dev-bin
  # flatpak packages
  - flatpak
  - gnome-software-plugin-flatpak

config_apt_list_2:
  - texstudio
  - texlive-full
  - texlive-extra-utils
  - texlive-latex-recommended
  - libmp3lame-dev
  - libfaac-dev
  - libfaad-dev
  - libxvidcore4
  - swh-plugins
  - cubic
  - icc-profiles
  - liblocale-codes-perl
  - gscan2pdf
  - octave
  - octave-doc
  - gnuplot 
  - virtualbox
  - virtualbox-qt
  - virtualbox-dkms
  - virtualbox-guest-additions-iso
  - virtualbox-ext-pack
  - woeusb
  - build-essential
  - git-lfs
  - android-tools-adb
  - esptool
  - autossh

# custom flatpak's
config_custom_flatpak:
  # - { package: "org.gimp.GIMP", repo: "flathub", state: present }
  # - { package: "org.inkscape.Inkscape", repo: "flathub", state: present }

config_flatpak_list_1:
  # Media
  - { package: "io.freetubeapp.FreeTube", repo: "flathub", state: present }
  - { package: "com.github.unrud.VideoDownloader", repo: "flathub", state: present }
  - { package: "org.flameshot.Flameshot", repo: "flathub", state: present }
  - { package: "org.gimp.GIMP", repo: "flathub", state: present }
  - { package: "org.inkscape.Inkscape", repo: "flathub", state: present }
  - { package: "org.gnome.Shotwell", repo: "flathub", state: present }
  # Voice chat / communication
  - { package: "com.teamspeak.TeamSpeak", repo: "flathub", state: present }
  - { package: "im.riot.Riot", repo: "flathub", state: present }
  # Documents
  - { package: "net.codeindustry.MasterPDFEditor", repo: "flathub", state: present }
  - { package: "com.github.xournalpp.xournalpp", repo: "flathub", state: present }
  - { package: "com.github.jeromerobert.pdfarranger", repo: "flathub", state: present }
  - { package: "org.libreoffice.LibreOffice", repo: "flathub", state: present }
  - { package: "com.vscodium.codium", repo: "flathub", state: present }
  # Browser
  - { package: "org.chromium.Chromium", repo: "flathub", state: present }
  - { package: "org.mozilla.firefox", repo: "flathub", state: present }
  - { package: "com.google.Chrome", repo: "flathub-beta", state: present }
  - { package: "com.github.Eloston.UngoogledChromium", repo: "flathub", state: present }
  # Miscellaneous
  - { package: "com.github.tchx84.Flatseal", repo: "flathub", state: present }
  - { package: "com.belmoussaoui.Decoder", repo: "flathub", state: present }
  - { package: "org.geogebra.GeoGebra", repo: "flathub", state: present }
  - { package: "org.keepassxc.KeePassXC", repo: "flathub", state: present }
  - { package: "org.gnome.Gnote", repo: "flathub", state: present }
  - { package: "com.gitlab.bitseater.meteo", repo: "flathub", state: present }
  - { package: "com.nextcloud.desktopclient.nextcloud", repo: "flathub", state: present }

config_flatpak_list_2:
  # Media
  - { package: "org.darktable.Darktable", repo: "flathub", state: present }
  - { package: "org.freecadweb.FreeCAD", repo: "flathub", state: present }
  - { package: "ink.scribl.Scribl", repo: "flathub", state: present }
  - { package: "org.audacityteam.Audacity", repo: "flathub", state: present }
  - { package: "org.js.nuclear.Nuclear", repo: "flathub", state: present }
  - { package: "org.kde.kdenlive", repo: "flathub", state: present }
  - { package: "fr.handbrake.ghb", repo: "flathub", state: present }
  - { package: "com.calibre_ebook.calibre", repo: "flathub", state: present }
  # Voice chat / communication
  - { package: "io.github.Soundux", repo: "flathub", state: present }
  - { package: "info.mumble.Mumble", repo: "flathub", state: present }
  - { package: "org.signal.Signal", repo: "flathub", state: present }
  # Documents
  - { package: "ch.openboard.OpenBoard", repo: "flathub", state: present }
  - { package: "io.typora.Typora", repo: "flathub", state: present }
  - { package: "net.scribus.Scribus", repo: "flathub", state: present }
  - { package: "com.wps.Office", repo: "flathub", state: present }
  # Miscellaneous
  - { package: "org.zotero.Zotero", repo: "flathub", state: present }
  - { package: "fr.romainvigier.MetadataCleaner", repo: "flathub", state: present }
  - { package: "de.willuhn.Jameica", repo: "flathub", state: present }

breitbandmessung_deb: "https://download.breitbandmessung.de/bbm/Breitbandmessung-linux.deb"