---
# extended software package
config_extended_software: false
# custom flatpak's

config_custom_flatpak:
  # - { package: "org.gimp.GIMP", repo: "flathub", state: present }
  # - { package: "org.inkscape.Inkscape", repo: "flathub", state: present }

config_flatpak_list:
  # Media
  - { package: "io.freetubeapp.FreeTube", repo: "flathub", state: present }
  - { package: "fr.handbrake.ghb", repo: "flathub", state: present }
  - { package: "com.github.unrud.VideoDownloader", repo: "flathub", state: present }
  - { package: "org.flameshot.Flameshot", repo: "flathub", state: present }
  # Voice chat / communication
  - { package: "org.signal.Signal", repo: "flathub", state: present }
  - { package: "com.teamspeak.TeamSpeak", repo: "flathub", state: present }
  - { package: "info.mumble.Mumble", repo: "flathub", state: present }
  # Documents
  - { package: "net.codeindustry.MasterPDFEditor", repo: "flathub", state: present }
  - { package: "com.github.xournalpp.xournalpp", repo: "flathub", state: present }
  - { package: "com.github.jeromerobert.pdfarranger", repo: "flathub", state: present }
  - { package: "org.libreoffice.LibreOffice", repo: "flathub", state: present }
  - { package: "com.wps.Office", repo: "flathub", state: present }
  # Browser
  - { package: "com.github.Eloston.UngoogledChromium", repo: "flathub", state: present }
  - { package: "org.chromium.Chromium", repo: "flathub", state: present }
  - { package: "org.mozilla.firefox", repo: "flathub", state: present }
  - { package: "com.google.Chrome", repo: "flathub-beta", state: present }
  # Miscellaneous
  - { package: "com.github.tchx84.Flatseal", repo: "flathub", state: present }
  - { package: "com.belmoussaoui.Decoder", repo: "flathub", state: present }
  - { package: "org.geogebra.GeoGebra", repo: "flathub", state: present }
  - { package: "fr.romainvigier.MetadataCleaner", repo: "flathub", state: present }
  - { package: "org.gimp.GIMP", repo: "flathub", state: present }
  - { package: "org.inkscape.Inkscape", repo: "flathub", state: present }

config_flatpak_list_extended:
  - { package: "org.zotero.Zotero", repo: "flathub", state: present }
  - { package: "io.github.Soundux", repo: "flathub", state: present }
  - { package: "org.darktable.Darktable", repo: "flathub", state: present }
  - { package: "org.freecadweb.FreeCAD", repo: "flathub", state: present }
  - { package: "ink.scribl.Scribl", repo: "flathub", state: present }
  - { package: "ch.openboard.OpenBoard", repo: "flathub", state: present }
  - { package: "org.audacityteam.Audacity", repo: "flathub", state: present }
  - { package: "io.typora.Typora", repo: "flathub", state: present }
  - { package: "org.js.nuclear.Nuclear", repo: "flathub", state: present }
  - { package: "org.kde.kdenlive", repo: "flathub", state: present }
  - { package: "net.scribus.Scribus", repo: "flathub", state: present }

