---
# custom wifi drivers

rtw89_repo_url: { url: "https://github.com/lwfinger/rtw89.git", version: 'main' }
rtw89_repo_dir: "/srv/rtw89"
ensure_rtw89_module: false

# graphic tool
enable_rembg: False
config_rembg_repo: { url: "https://github.com/danielgatis/rembg.git", version: 'main', dir: "/srv/rembg" }

# linuxrouter commit

config_linuxrouter_commit: "f8cbf5eded1d912ea686f08d2214afed5ed0cd5e"

# extended software package
config_extended_software: false

# downgrade custom package

config_downgrade: false

# generate config file

config_generate_config_file: false

# pipewire

config_pipewire_enabled: False

# Software details

config_apt_keys: []
  # - { url: "https://pkg.cloudflare.com/cloudflare-main.gpg", state: "present", dest: "/usr/share/keyrings/cloudflare-main.gpg" }

config_apt_keys_curl: []
  # - { url: "https://pkg.cloudflare.com/cloudflare-main.gpg", state: "present", dest: "/usr/share/keyrings/cloudflare-main.gpg" }
  
config_apt_sources:
  - { repo: "deb http://www.geogebra.net/linux/ stable main", state: "absent", filename: "geogebra" }

config_apt_ppa_list_1:
  # Present
  - { ppa: "ppa:marko-preuss/hibiscus", state: "present", ubuntu_max_release: 20 }
  - { ppa: "ppa:ubuntu-mozilla-security/ppa", state: "present", ubuntu_max_release: 20 }
  - { ppa: "ppa:unit193/encryption", state: "present", ubuntu_max_release: 22 }
  - { ppa: "ppa:alexlarsson/flatpak", state: "present", ubuntu_max_release: 20 }
  - { ppa: "ppa:recoll-backports/recoll-1.15-on", state: "present", ubuntu_max_release: 18 }
  # Choice
  - { ppa: "ppa:pipewire-debian/pipewire-upstrshcam", state: "{{ 'present' if config_pipewire_enabled|bool else 'absent' }}", ubuntu_max_release: 22 }
  # Absent
  - { ppa: "ppa:nextcloud-devs/client", state: "absent", ubuntu_max_release: 20 }
  - { ppa: "ppa:andreasbutti/xournalpp-master", state: "absent", ubuntu_max_release: 20 }
  - { ppa: "ppa:apandada1/xournalpp-stable", state: "absent", ubuntu_max_release: 20 }
  - { ppa: "ppa:smathot/cogscinl", state: "absent", ubuntu_max_release: 20 }

config_apt_ppa_list_2:
  - { ppa: "ppa:tomtomtom/woeusb", state: "present" , ubuntu_max_release: 22 }
  - { ppa: "ppa:cubic-wizard/release", state: "present", ubuntu_max_release: 22 }

config_apt_list_1:
  - curl
  - openssh-server
  - gparted
  - byobu
  - snapd
  - zsh
  - wget
  - dnsutils
  - nethogs
  - git
  - git-gui
  - sudo
  - htop
  - powertop
  - bmon
  - shc
  - vim
  - nano
  - pwgen
  - nautilus
  - vlc
  - libxvidcore4
  - vlc-plugin-fluidsynth
  - vlc-plugin-jack
  - libdvdnav4
  - gstreamer1.0-plugins-bad
  - gstreamer1.0-plugins-ugly
  - ubuntu-restricted-extras
  - software-properties-common
  - audacious
  - audacious-plugins
  - poppler-utils
  - ocrmypdf
  - tesseract-ocr
  - tesseract-ocr-deu
  - libfaac0
  - rclone
  - restic
  - clamav
  - clamav-freshclam
  - clamtk
  - gcc
  - wipe
  - unzip
  - p7zip
  - p7zip-full
  - p7zip-rar
  - tar
  - htop
  - aha
  - qpdf
  - screen
  - ncdu
  - dos2unix
  - speedtest-cli
  - net-tools
  - traceroute
  - imagemagick
  - nautilus-image-converter
  - gnuplot
  - gnuplot-x11
  - gnuplot-doc
  - recoll
  - poppler-utils
  - gnome-shell-extensions
  - gnome-clocks
  - mupdf-tools
  - pdfposter
  - pdfsam
  - img2pdf
  - inxi
  - txt2html
  - wkhtmltopdf
  - qtqr
  - macchanger
  - youtube-dl
  - autossh
  - zbar-tools
  - texlive-extra-utils
  - ca-certificates
  - hplip
  - libreoffice-common
  - python3
  - python3-pip
  - veracrypt
  - simple-scan
  - usb-creator-gtk
  - gnome-tweaks
  - gnome-shell-extensions
  - gettext
  - sassc
  - libglib2.0-dev-bin
  - libatlas-base-dev
  - flatpak
  - gnome-software-plugin-flatpak
  - dbus-x11
  - nautilus-actions
  - gnome-terminal
  - ubuntu-desktop

config_apt_list_2:
  - texstudio
  - texlive-full
  - texlive-extra-utils
  - texlive-latex-recommended
  - latex2html
  - libmp3lame-dev
  - libfaac-dev
  - libfaad-dev
  - libxvidcore4
  - swh-plugins
  - cubic
  - icc-profiles
  - liblocale-codes-perl
  - gscan2pdf
  - octave
  - octave-doc
  - gnuplot 
  - virtualbox
  - virtualbox-qt
  - virtualbox-dkms
  - virtualbox-guest-additions-iso
  - virtualbox-ext-pack
  - woeusb
  - build-essential
  - git-lfs
  - esptool
  - ldap-utils
  - autossh

config_apt_list_absent:
  - xournalpp
  - master-pdf-editor
  - zotero-standalone
  - geogebra-classic
  - libreoffice-draw
  - libreoffice-calc
  - libreoffice-impress
  - libreoffice-writer
  - darktable
  - freecad
  - signal-desktop
  - restic
  - gimp
  - inkscape
  - chromium-browser
  - chromium-codecs-ffmpeg-extra
  - firefox
  - kdenlive
  - scribus
  - scribus-doc
  - scribus-template
  - shotwell
  - hibiscus-ppa
  - speedtest-cli
  - codium
  - nextcloud-client
  - nautilus-wipe
  - breitbandmessung

config_apt_pipewire:
  - pipewire
  - pipewire-audio-client-libraries
  - gstreamer1.0-pipewire
  - libpipewire-0.3-0
  - libpipewire-0.3-dev
  - libpipewire-0.3-modules
  - libspa-0.2-bluetooth
  - libspa-0.2-dev
  - libspa-0.2-jack
  - libspa-0.2-modules
  - pipewire-pulse
  - pipewire-media-session
  - pipewire-bin
  - pipewire-locales
  - pipewire-tests

# custom flatpak's
config_custom_flatpak:
  # - { package: "org.gimp.GIMP", repo: "flathub", state: present }
  # - { package: "org.inkscape.Inkscape", repo: "flathub", state: present }

config_flatpak_list_1:
  # Media
  - { package: "io.freetubeapp.FreeTube", repo: "flathub", state: present }
  - { package: "com.github.unrud.VideoDownloader", repo: "flathub", state: present }
  - { package: "org.flameshot.Flameshot", repo: "flathub", state: present }
  - { package: "org.gimp.GIMP", repo: "flathub", state: present }
  - { package: "org.inkscape.Inkscape", repo: "flathub", state: present }
  - { package: "org.gnome.Shotwell", repo: "flathub", state: present }
  - { package: "org.gnome.NetworkDisplays", repo: "flathub", state: "{{ 'present' if ansible_facts['lsb']['major_release']| int == 2 else 'absent' }}" }
  - { package: "com.makemkv.MakeMKV", repo: "flathub", state: present }
  - { package: "fr.handbrake.ghb", repo: "flathub", state: present }
  # Voice chat / communication
  - { package: "com.teamspeak.TeamSpeak", repo: "flathub", state: present }
  - { package: "im.riot.Riot", repo: "flathub", state: present }
  - { package: "org.jitsi.jitsi-meet", repo: "flathub", state: present }
  # Documents
  - { package: "net.codeindustry.MasterPDFEditor", repo: "flathub", state: present }
  - { package: "com.github.xournalpp.xournalpp", repo: "flathub", state: present }
  - { package: "com.github.jeromerobert.pdfarranger", repo: "flathub", state: present }
  - { package: "org.libreoffice.LibreOffice", repo: "flathub", state: present }
  - { package: "com.vscodium.codium", repo: "flathub", state: present }
  - { package: "re.sonny.Junction", repo: "flathub", state: present }
  # Browser
  - { package: "org.chromium.Chromium", repo: "flathub", state: present }
  - { package: "org.mozilla.firefox", repo: "flathub", state: present }
  - { package: "com.google.Chrome", repo: "flathub", state: present }
  - { package: "com.github.Eloston.UngoogledChromium", repo: "flathub", state: present }
  # Miscellaneous
  - { package: "com.github.tchx84.Flatseal", repo: "flathub", state: present }
  - { package: "de.breitbandmessung.Breitbandmessung", repo: "flathub", state: present }
  - { package: "com.belmoussaoui.Authenticator", repo: "flathub", state: present }
  - { package: "com.belmoussaoui.Decoder", repo: "flathub", state: present }
  - { package: "org.keepassxc.KeePassXC", repo: "flathub", state: present }
  - { package: "org.gnome.Gnote", repo: "flathub", state: present }
  - { package: "com.gitlab.bitseater.meteo", repo: "flathub", state: present }
  - { package: "com.mattjakeman.ExtensionManager", repo: "flathub", state: present }
  - { package: "io.kopia.KopiaUI", repo: "flathub", state: present }
  - { package: "org.cryptomator.Cryptomator", repo: "flathub", state: present }
  - { package: "io.github.peazip.PeaZip", repo: "flathub", state: present }
  - { package: "com.nextcloud.desktopclient.nextcloud", repo: "flathub", state: present }
  # Game
  - { package: "com.teeworlds.Teeworlds", repo: "flathub", state: present }

config_flatpak_list_2:
  # Media
  - { package: "org.darktable.Darktable", repo: "flathub", state: present }
  - { package: "org.freecadweb.FreeCAD", repo: "flathub", state: present }
  - { package: "ink.scribl.Scribl", repo: "flathub", state: present }
  - { package: "org.audacityteam.Audacity", repo: "flathub", state: present }
  - { package: "org.js.nuclear.Nuclear", repo: "flathub", state: present }
  - { package: "org.kde.kdenlive", repo: "flathub", state: present }
  - { package: "com.calibre_ebook.calibre", repo: "flathub", state: present }
  # Voice chat / communication
  - { package: "io.github.Soundux", repo: "flathub", state: present }
  - { package: "info.mumble.Mumble", repo: "flathub", state: present }
  - { package: "org.signal.Signal", repo: "flathub", state: present }
  # Documents
  - { package: "ch.openboard.OpenBoard", repo: "flathub", state: present }
  - { package: "io.typora.Typora", repo: "flathub", state: present }
  - { package: "net.scribus.Scribus", repo: "flathub", state: present }
  - { package: "com.wps.Office", repo: "flathub", state: present }
  # Miscellaneous
  - { package: "org.zotero.Zotero", repo: "flathub", state: present }
  - { package: "fr.romainvigier.MetadataCleaner", repo: "flathub", state: present }
  - { package: "de.willuhn.Jameica", repo: "flathub", state: present }
  # - { package: "org.geogebra.GeoGebra", repo: "flathub", state: present }

### PUSH GATEWAY
gotify_notify_dest:
  - {host: "push.hilberg.eu", key: "AGYHlNHiACJ9TCo"}

### MIMETYPES
config_mimetypes: False

mimetype_default_apps_for:
  audio: "audacious.desktop"
  video: "vlc.desktop"
  web: "com.google.Chrome.desktop"

junction_mimetypes_apps:
  - mime: "application/pdf"
    apps:
      - org.gnome.Evince.desktop
      - com.github.jeromerobert.pdfarranger.desktop
      - net.codeindustry.MasterPDFEditor.desktop
      - org.libreoffice.LibreOffice.draw.desktop
  - mime: "application/zip"
    apps:
      - org.gnome.FileRoller.desktop
      - org.geogebra.GeoGebra.desktop

mimetypes_default_apps:
  # MANAGED WITH JUNCTION
  - { mime: "application/pdf", app: "re.sonny.Junction.desktop" }
  - { mime: "application/zip", app: "re.sonny.Junction.desktop" }
  # ETC
  - { mime: "application/x-php", app: "com.vscodium.codium.desktop" }
  - { mime: "text/markdown", app: "io.typora.Typora.desktop" }
  - { mime: "text/x-tex", app: "texstudio.desktop" }
  - { mime: "application/vnd.appimage", app: "nautilus-autorun-software.desktop" }
  - { mime: "application/vnd.oasis.opendocument.text", app: "org.libreoffice.LibreOffice.writer.desktop" }
  - { mime: "application/rtf", app: "org.gnome.gedit.desktop" }
  - { mime: "application/json", app: "com.vscodium.codium.desktop" }
  - { mime: "x-scheme-handler/etcher", app: "balena-etcher-electron.desktop" }
  - { mime: "image/heif", app: "org.gnome.eog.desktop" }
  - { mime: "application/x-yaml", app: "com.vscodium.codium.desktop" }
  - { mime: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", app: "org.libreoffice.LibreOffice.writer.desktop" }
  - { mime: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", app: "org.libreoffice.LibreOffice.calc.desktop" }
  - { mime: "application/vnd.ms-excel", app: "org.libreoffice.LibreOffice.calc.desktop" }
  - { mime: "application/msword", app: "org.libreoffice.LibreOffice.writer.desktop" }
  - { mime: "application/x-shellscript", app: "com.vscodium.codium.desktop" }
  - { mime: "text/html", app: "{{ mimetype_default_apps_for.web }}" }
  - { mime: "application/xhtml+xml", app: "{{ mimetype_default_apps_for.web }}" }
  - { mime: "x-scheme-handler/http", app: "{{ mimetype_default_apps_for.web }}" }
  - { mime: "x-scheme-handler/https", app: "{{ mimetype_default_apps_for.web }}" }
  - { mime: "x-scheme-handler/about", app: "{{ mimetype_default_apps_for.web }}" }
  - { mime: "x-scheme-handler/unknown", app: "{{ mimetype_default_apps_for.web }}" }
  - { mime: "image/svg+xml", app: "org.inkscape.Inkscape.desktop" }
  - { mime: "application/x-ms-dos-executable", app: "wine.desktop" }
  - { mime: "application/x-wine-extension-ini", app: "org.gnome.gedit.desktop" }
  - { mime: "video/x-matroska", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/mp4", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/x-msvideo", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "x-scheme-handler/webcal", app: "{{ mimetype_default_apps_for.web }}" }
  - { mime: "text/plain", app: "org.gnome.gedit.desktop" }
  - { mime: "application/vnd.geogebra.file", app: "org.geogebra.GeoGebra.desktop" }
  - { mime: "application/vnd.geogebra-classic.file", app: "org.geogebra.GeoGebra.desktop" }
  - { mime: "x-scheme-handler/mailto", app: "thunderbird.desktop" }
  - { mime: "message/rfc822", app: "userapp-Thunderbird-08GXI0.desktop" }
  # AUDIO
  - { mime: "audio/x-vorbis+ogg", app: "{{ mimetype_default_apps_for.audio }}" }
  - { mime: "audio/midi", app: "{{ mimetype_default_apps_for.audio }}" }
  - { mime: "audio/mp3", app: "{{ mimetype_default_apps_for.audio }}" }
  - { mime: "audio/mp4", app: "{{ mimetype_default_apps_for.audio }}" }
  - { mime: "audio/mpeg", app: "{{ mimetype_default_apps_for.audio }}" }
  - { mime: "audio/mpegurl", app: "{{ mimetype_default_apps_for.audio }}" }
  - { mime: "audio/ogg", app: "{{ mimetype_default_apps_for.audio }}" }
  - { mime: "audio/prs.sid", app: "{{ mimetype_default_apps_for.audio }}" }
  - { mime: "audio/x-flac", app: "{{ mimetype_default_apps_for.audio }}" }
  - { mime: "audio/x-it", app: "{{ mimetype_default_apps_for.audio }}" }
  - { mime: "audio/x-mod", app: "{{ mimetype_default_apps_for.audio }}" }
  - { mime: "audio/x-mp3", app: "{{ mimetype_default_apps_for.audio }}" }
  - { mime: "audio/x-mpeg", app: "{{ mimetype_default_apps_for.audio }}" }
  - { mime: "audio/x-mpegurl", app: "{{ mimetype_default_apps_for.audio }}" }
  - { mime: "audio/x-ms-asx", app: "{{ mimetype_default_apps_for.audio }}" }
  - { mime: "audio/x-ms-wma", app: "{{ mimetype_default_apps_for.audio }}" }
  - { mime: "audio/x-musepack", app: "{{ mimetype_default_apps_for.audio }}" }
  - { mime: "audio/x-s3m", app: "{{ mimetype_default_apps_for.audio }}" }
  - { mime: "audio/x-scpls", app: "{{ mimetype_default_apps_for.audio }}" }
  - { mime: "audio/x-stm", app: "{{ mimetype_default_apps_for.audio }}" }
  - { mime: "audio/x-wav", app: "{{ mimetype_default_apps_for.audio }}" }
  - { mime: "audio/x-xm", app: "{{ mimetype_default_apps_for.audio }}" }
  # VIDEO
  - { mime: "video/x-ogm+ogg", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/ogg", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/x-ogm", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/x-theora+ogg", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/x-theora", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/x-ms-asf", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/x-ms-asf-plugin", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/x-ms-asx", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/x-ms-wm", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/x-ms-wmv", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/x-ms-wmx", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/x-ms-wvx", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/divx", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/msvideo", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/vnd.divx", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/avi", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/x-avi", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/vnd.rn-realvideo", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/mp2t", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/mpeg", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/mpeg-system", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/x-mpeg", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/x-mpeg2", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/x-mpeg-system", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/mp4v-es", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/x-m4v", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/quicktime", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/webm", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/3gp", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/3gpp", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/3gpp2", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/vnd.mpegurl", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/dv", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/x-anim", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/x-nsv", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/fli", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/flv", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/x-flc", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/x-fli", app: "{{ mimetype_default_apps_for.video }}" }
  - { mime: "video/x-flv", app: "{{ mimetype_default_apps_for.video }}" }

# extra roles
extra_roles_prefix: "hdhweg-extra-"
extra_roles_base_dir: "/root/.ansible/roles"
extra_roles: []
  # - repo: "git.server.xyz/user/repo.git"
  #   version: "master"
  #   name: "myrolename"
  #   user: "gituser"
  #   key: "gitapikey"