---
- name: Check if Ollama is installed using which
  command: which ollama
  register: ollama_command
  ignore_errors: true

- name: Set fact for Ollama installation check
  set_fact:
    ollama_installed: "{{ ollama_command.rc == 0 }}"

- name: Install ollama
  block:
    - name: Download the installation script
      get_url:
        url: https://ollama.com/install.sh
        dest: /tmp/install_ollama.sh
        mode: '0755'

    - name: Execute the installation script
      command: /tmp/install_ollama.sh
      register: install_output
  when: ollama_enabled|bool and not ollama_installed

- name: Ensure ollama settings
  block:
    - name: Pull models
      command: ollama pull {{ item }}
      loop: "{{ ollama_models }}"
      ignore_errors: true
  when: ollama_enabled|bool

- name: "Ensure Ollama service is in the desired state: {{ ollama_enabled|bool | ternary('started', 'stopped') }}"
  service:
    name: ollama
    state: "{{ ollama_enabled|bool | ternary('started', 'stopped') }}"
    enabled: "{{ ollama_enabled|bool | ternary(true, false) }}"
