---
- name: Ensure nextcloud-client ppa
  apt_repository:
    repo: ppa:nextcloud-devs/client

- name: Add geogebra key
  apt_key:
    url: https://static.geogebra.org/linux/office@geogebra.org.gpg.key
    state: present

- name: Add geogebra repository
  apt_repository:
    repo: deb http://www.geogebra.net/linux/ stable main
    state: present
    filename: geogebra

- name: Add teamviewer key
  apt_key:
    url: https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc
    state: present
  when: ansible_facts['lsb']['id'] == "Ubuntu" and ansible_facts['lsb']['major_release']| int < 20

- name: Add teamviewer repository
  apt_repository:
    repo: deb http://linux.teamviewer.com/deb stable main
    state: present
  when: ansible_facts['lsb']['id'] == "Ubuntu" and ansible_facts['lsb']['major_release']| int < 20

- name: Ensure recoll ppa
  apt_repository:
    repo: ppa:recoll-backports/recoll-1.15-on
  when: ansible_facts['lsb']['id'] == "Ubuntu" and ansible_facts['lsb']['major_release']| int < 20

- name: Ensure veracrypt ppa
  apt_repository:
    repo: ppa:unit193/encryption
  when: ansible_facts['lsb']['id'] == "Ubuntu" and ansible_facts['lsb']['major_release']| int < 20

- name: Ensure xournal ppa
  apt_repository:
    repo: ppa:andreasbutti/xournalpp-master
  when: ansible_facts['lsb']['id'] == "Ubuntu" and ansible_facts['lsb']['major_release']| int < 20

- name: Ensure zotero ppa
  apt_repository:
    repo: ppa:smathot/cogscinl
  when: ansible_facts['lsb']['id'] == "Ubuntu" and ansible_facts['lsb']['major_release']| int < 20

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: safe

- name: Ensure packages
  apt:
    name:
      - byobu
      - snapd
      - zsh
      - curl
      - wget
      - dnsutils
      - git
      - sudo
      - htop
      - vim
      - nano
      - nautilus
      - libreoffice
      - vlc
      - libxvidcore4
      - vlc-plugin-fluidsynth
      - vlc-plugin-jack
      - libdvdnav4
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - ubuntu-restricted-extras
      - software-properties-common
      - audacious
      - audacious-plugins
      - poppler-utils
      - chromium-browser
      - chromium-codecs-ffmpeg-extra
      - gimp
      - inkscape
      - gscan2pdf
      - ocrmypdf
      - tesseract-ocr
      - tesseract-ocr-deu
      - libfaac0
      - rclone
      - restic
      - clamav
      - clamav-freshclam
      - clamtk
      - gcc
      - wipe
      - unzip
      - p7zip
      - p7zip-full
      - p7zip-rar
      - tar
      - htop
      - screen
      - ncdu
      - dos2unix
      - speedtest-cli
      - net-tools
      - imagemagick
      - gnuplot
      - gnuplot-x11
      - gnuplot-doc
      - recoll
      - poppler-utils
      - python3
      - python3-pip
      - gnome-shell-extensions
      - youtube-dl
      - gnome-clocks
      - mupdf-tools
      - pdfposter
      - pdfsam
      - img2pdf
      - geogebra-classic
      - inxi
      - txt2html
      - wkhtmltopdf
      - gnome-shell-extensions
      - chrome-gnome-shell
      - nextcloud-client
    state: latest
    install_recommends: yes

- name: Ensure some other packages
  apt:
    name:
      - teamviewer
      - xournalpp
      - veracrypt
      - zotero-standalone
    state: latest
    install_recommends: yes
  when: ansible_facts['lsb']['id'] == "Ubuntu" and ansible_facts['lsb']['major_release']| int < 20