---
- name: Ensure ppa's states
  apt_repository:
    repo: "{{ item.ppa }}"
    state: "{{ item.state }}"
  loop:
    - { ppa: "ppa:nextcloud-devs/client", state: "present"}
    - { ppa: "ppa:ubuntu-mozilla-security/ppa", state: "present"}
    - { ppa: "ppa:unit193/encryption", state: "present"}
    - { ppa: "ppa:andreasbutti/xournalpp-master", state: "absent"}
    - { ppa: "ppa:apandada1/xournalpp-stable", state: "absent"}
    - { ppa: "ppa:smathot/cogscinl", state: "absent"}

- name: Ensure ppa's states (< Ubuntu 20)
  apt_repository:
    repo: "{{ item.ppa }}"
    state: "{{ item.state }}"
  loop:
    - { ppa: "ppa:recoll-backports/recoll-1.15-on", state: "present"}
  when: ansible_facts['lsb']['id'] == "Ubuntu" and ansible_facts['lsb']['major_release']| int < 20

- name: Ensure key states
  apt_key:
    url: "{{ item.url }}"
    state: "{{ item.state }}"
  loop:
    - { url: "https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg", state: "present"}
    - { url: "https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc", state: "present"}

- name: Ensure source states
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
    filename: "{{ item.filename }}"
  loop:
    - { repo: "deb http://www.geogebra.net/linux/ stable main", state: "absent", filename: "geogebra"}
    - { repo: "deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main", state: "present", filename: "vscodium"}
    - { repo: "deb http://linux.teamviewer.com/deb stable main", state: "present", filename: "teamviewer"}


- name: Update apt (this might take a long time)
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: safe

- name: Ensure packages (this might take a looooong time)
  apt:
    name:
      - curl
      - openssh-server
      - gparted
      - byobu
      - snapd
      - zsh
      - wget
      - dnsutils
      - git
      - git-gui
      - sudo
      - htop
      - bmon
      - vim
      - nano
      - nautilus
      - vlc
      - libxvidcore4
      - vlc-plugin-fluidsynth
      - vlc-plugin-jack
      - libdvdnav4
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - ubuntu-restricted-extras
      - software-properties-common
      - audacious
      - audacious-plugins
      - poppler-utils
      - ocrmypdf
      - tesseract-ocr
      - tesseract-ocr-deu
      - libfaac0
      - rclone
      - restic
      - clamav
      - clamav-freshclam
      - clamtk
      - gcc
      - wipe
      - unzip
      - p7zip
      - p7zip-full
      - p7zip-rar
      - tar
      - htop
      - screen
      - ncdu
      - dos2unix
      - speedtest-cli
      - net-tools
      - imagemagick
      - gnuplot
      - gnuplot-x11
      - gnuplot-doc
      - recoll
      - poppler-utils
      - gnome-shell-extensions
      - gnome-clocks
      - mupdf-tools
      - pdfposter
      - pdfsam
      - img2pdf
      - inxi
      - txt2html
      - wkhtmltopdf
      - nextcloud-client
      - qtqr
      - macchanger
      - youtube-dl
      - teamviewer
      - autossh
      - zbar-tools
      - texlive-extra-utils
      - ca-certificates
      - codium
      - hplip
      - libreoffice-common
      - python3
      - python3-pip
      - veracrypt
      - simple-scan
      - nautilus-wipe
      - usb-creator-gtk
    state: latest
    install_recommends: yes

- name: Ensure apt packages absent
  apt:
    name:
      - xournalpp
      - master-pdf-editor
      - zotero-standalone
      - geogebra-classic
      - libreoffice-draw
      - libreoffice-calc
      - libreoffice-impress
      - libreoffice-writer
      - darktable
      - freecad
      - signal-desktop
      - restic
      - gimp
      - inkscape
      - chromium-browser
      - chromium-codecs-ffmpeg-extra
      - firefox
    state: absent

- name: Ensure packages for ubuntu => 20
  apt:
    name:
      - python-is-python3
    state: latest
    install_recommends: yes
  when: ansible_facts['lsb']['id'] == "Ubuntu" and ansible_facts['lsb']['major_release']| int == 20

- name: Query duplicati releases from github
  uri:                                                               
    url: https://api.github.com/repos/duplicati/duplicati/releases
    return_content: true                                             
  register: duplicati_source   
  ignore_errors: yes                                          

- name: Register duplicati deb url
  set_fact:
    duplicati_deb:  "{{ duplicati_source.json[0]['assets'] | selectattr('browser_download_url', 'contains', 'all.deb') | list }}"
  ignore_errors: yes

- name: Ensure duplicati
  apt:
    deb: "{{ duplicati_deb[0]['browser_download_url'] }}"
  ignore_errors: yes

- name: Update all dist packages to the latest version
  apt:
    upgrade: dist

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
