---
- name: Ensure nextcloud-client ppa
  apt_repository:
    repo: ppa:nextcloud-devs/client

- name: Ensure absent geogebra repository
  apt_repository:
    repo: deb http://www.geogebra.net/linux/ stable main
    state: absent
    filename: geogebra

- name: Add VScodium key
  apt_key:
    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    state: present

- name: Add VScodium repository
  apt_repository:
    repo: deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main
    state: present
    filename: vscodium

- name: Add teamviewer key
  apt_key:
    url: https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc
    state: present
  when: ansible_facts['lsb']['id'] == "Ubuntu" and ansible_facts['lsb']['major_release']| int <= 20

- name: Add teamviewer repository
  apt_repository:
    repo: deb http://linux.teamviewer.com/deb stable main
    state: present
    filename: teamviewer
  when: ansible_facts['lsb']['id'] == "Ubuntu" and ansible_facts['lsb']['major_release']| int <= 20

- name: Ensure thunderbird ppa
  apt_repository:
    repo: ppa:ubuntu-mozilla-security/ppa

- name: Ensure recoll ppa
  apt_repository:
    repo: ppa:recoll-backports/recoll-1.15-on
  when: ansible_facts['lsb']['id'] == "Ubuntu" and ansible_facts['lsb']['major_release']| int < 20

- name: Ensure veracrypt ppa
  apt_repository:
    repo: ppa:unit193/encryption

- name: Ensure no unstable xournal ppa is present
  apt_repository:
    repo: ppa:andreasbutti/xournalpp-master
    state: absent
  when: ansible_facts['lsb']['id'] == "Ubuntu" and ansible_facts['lsb']['major_release']| int <= 20

- name: Ensure no xournal ppa is present
  apt_repository:
    repo: ppa:apandada1/xournalpp-stable
    state: absent

- name: Ensure zotero ppa
  apt_repository:
    repo: ppa:smathot/cogscinl
    state: absent

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: safe

- name: Upgrade all apt packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Update all dist packages to the latest version
  apt:
    upgrade: dist

- name: Ensure packages (this might take a looooong time)
  apt:
    name:
      - curl
      - openssh-server
      - gparted
      - byobu
      - snapd
      - zsh
      - wget
      - dnsutils
      - git
      - sudo
      - htop
      - bmon
      - vim
      - nano
      - nautilus
      - vlc
      - libxvidcore4
      - vlc-plugin-fluidsynth
      - vlc-plugin-jack
      - libdvdnav4
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - ubuntu-restricted-extras
      - software-properties-common
      - audacious
      - audacious-plugins
      - poppler-utils
      - chromium-browser
      - chromium-codecs-ffmpeg-extra
      - ocrmypdf
      - tesseract-ocr
      - tesseract-ocr-deu
      - libfaac0
      - rclone
      - restic
      - clamav
      - clamav-freshclam
      - clamtk
      - gcc
      - wipe
      - unzip
      - p7zip
      - p7zip-full
      - p7zip-rar
      - tar
      - htop
      - screen
      - ncdu
      - dos2unix
      - speedtest-cli
      - net-tools
      - imagemagick
      - gnuplot
      - gnuplot-x11
      - gnuplot-doc
      - recoll
      - poppler-utils
      - gnome-shell-extensions
      - gnome-clocks
      - mupdf-tools
      - pdfposter
      - pdfsam
      - img2pdf
      - inxi
      - txt2html
      - wkhtmltopdf
      - chrome-gnome-shell
      - nextcloud-client
      - qtqr
      - macchanger
      - youtube-dl
      - teamviewer
      - autossh
      - zbar-tools
      - texlive-extra-utils
      - ca-certificates
      - codium
      - hplip
      - libreoffice-common
      - python3
      - python3-pip
      - veracrypt
      - simple-scan
      - nautilus-wipe
    state: latest
    install_recommends: yes

- name: Ensure packages absent
  apt:
    name:
      - xournalpp
      - master-pdf-editor
      - zotero-standalone
      - geogebra-classic
      - libreoffice-draw
      - libreoffice-calc
      - libreoffice-impress
      - libreoffice-writer
      - darktable
      - freecad
      - signal-desktop
      - restic
      - gimp
      - inkscape
    state: absent

- name: Ensure packages for ubuntu => 20
  apt:
    name:
      - python-is-python3
    state: latest
    install_recommends: yes
  when: ansible_facts['lsb']['id'] == "Ubuntu" and ansible_facts['lsb']['major_release']| int == 20

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
