---
- name: Ensure flatpak ppa
  apt_repository:
    repo: ppa:alexlarsson/flatpak

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: safe

- name: Ensure flatpak package
  apt:
    name:
      - flatpak
      - gnome-software-plugin-flatpak
    state: latest
    install_recommends: yes

- name: Ensure flathub flatpak repository remotes
  flatpak_remote:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    flatpakrepo_url: "{{ item.repo }}"
  loop:
    - { repo: "https://dl.flathub.org/repo/flathub.flatpakrepo", name: "flathub", state: "present" }
    - { repo: "https://flathub.org/beta-repo/flathub-beta.flatpakrepo", name: "flathub-beta", state: "present" }

- name: Register flatpak list
  set_fact:
    flatpak_list:
     # Media
     - io.freetubeapp.FreeTube
     - fr.handbrake.ghb
     - com.github.unrud.VideoDownloader
     - org.flameshot.Flameshot
     # Voice chat / communication
     - org.signal.Signal
     - com.teamspeak.TeamSpeak
     - info.mumble.Mumble
     # Documents
     - net.codeindustry.MasterPDFEditor
     - com.github.xournalpp.xournalpp
     - com.github.jeromerobert.pdfarranger
     - org.libreoffice.LibreOffice
     - com.wps.Office
     # Browser
     - com.github.Eloston.UngoogledChromium
     - org.chromium.Chromium
     - org.mozilla.firefox
     # Miscellaneous
     - com.github.tchx84.Flatseal
     - com.belmoussaoui.Decoder
     - org.geogebra.GeoGebra
     - fr.romainvigier.MetadataCleaner
     - org.gimp.GIMP
     - org.inkscape.Inkscape

- name: Ensure verify flatpaks
  shell: "flatpak repair"
  become: yes

- name: Install flatpak packages
  flatpak:
    remote: flathub
    name: "{{ item }}"
    state: present
  with_items: "{{ flatpak_list }}"

- name: Install flatpak beta packages
  flatpak:
    remote: flathub-beta
    name: "{{ item }}"
    state: present
  with_items:
     - com.google.Chrome

- name: Ensure flatpaks up-to-date
  shell: "flatpak update -y {{ item }}"
  become: yes
  with_items: "{{ flatpak_list }}"
