---
- name: Ensure flathub flatpak repository remotes
  flatpak_remote:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    flatpakrepo_url: "{{ item.repo }}"
  loop:
    - { repo: "https://dl.flathub.org/repo/flathub.flatpakrepo", name: "flathub", state: "present" }
    - { repo: "https://flathub.org/beta-repo/flathub-beta.flatpakrepo", name: "flathub-beta", state: "present" }

- name: Ensure verify flatpaks
  shell: "flatpak repair"
  become: yes

- name: Install flatpak packages
  flatpak:
    remote: "{{ item.repo }}"
    name: "{{ item.package }}"
    state: "{{ item.state }}"
  with_items: "{{ config_flatpak_list }}"

- name: Triggering flatpak upgrade handler
  assert: { that: true, quiet: true }
  changed_when: true
  notify:
    - autoremove flatpaks
    - update flatpaks
    - update flatpak versions