---
- name: Ensure flathub flatpak repository remotes
  flatpak_remote:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    flatpakrepo_url: "{{ item.repo }}"
  loop:
    - { repo: "https://dl.flathub.org/repo/flathub.flatpakrepo", name: "flathub", state: "present" }
    - { repo: "https://flathub.org/beta-repo/flathub-beta.flatpakrepo", name: "flathub-beta", state: "present" }

# UPDATING FOR EACH PACKAGE
# - name: update flatpaks
#   shell: "flatpak update {{ item.package }} -y"
#   with_items: "{{ config_flatpak_list }}"
#   when: "(item.version is not defined) and (item.state=='present')"

# - name: repair flatpak
#   shell: "flatpak repair"
#   become: yes

- name: Update and repair flatpaks
  block:
    - name: update flatpaks
      shell: "flatpak update -y"
      become: yes
  rescue:
    - name: repair flatpak
      shell: "flatpak repair"
      become: yes
  ignore_errors: yes

- name: Gather Flatpak configuration
  block:
    - name: Ensure custom list is not None
      set_fact:
        config_custom_flatpak: "{{ config_custom_flatpak | default([], true) }}"
      when: config_custom_flatpak is none

    - name: Get list of masked flatpaks
      shell: "flatpak mask | tail -n +1"
      register: flatpak_masked_raw
      changed_when: false

    - name: Get list of installed flatpaks
      shell: "flatpak --columns=app list"
      register: flatpak_installed_raw
      changed_when: false

    - name: Map results to list facts
      set_fact:
        flatpak_masked: "{{ flatpak_masked_raw.stdout_lines }}"
        flatpak_installed_list: "{{ flatpak_installed_raw.stdout_lines }}"

  rescue:
    - name: Set default empty lists on failure
      set_fact:
        flatpak_masked: []
        flatpak_installed_list: []
        config_custom_flatpak: "{{ config_custom_flatpak | default([]) }}"

- name: Set facts
  set_fact:
    config_flatpak_list: "{% if config_extended_software|bool %}{{ config_custom_flatpak + config_flatpak_list_1 + config_flatpak_list_2 }}{% else %}{{ config_custom_flatpak + config_flatpak_list_1 }}{% endif %}"
    flatpak_masked_list: "{{ flatpak_masked.stdout_lines | map('trim') | list }}"
    flatpak_installed_list: "{{ flatpak_installed_list.stdout_lines | map('trim') | list }}"
  ignore_errors: yes

- name: Ensure flatpak packages
  flatpak:
    remote: "{{ item.repo }}"
    name: "{{ item.package }}"
    state: "{{ item.state }}"
  with_items: "{{ config_flatpak_list }}"
  ignore_errors: yes

- name: Triggering flatpak upgrade handler
  assert: { that: true, quiet: true }
  changed_when: true
  when: "not config_perform_apt_upgrade|default(false) and 'deploy' not in ansible_run_tags"
  notify:
    - autoremove flatpaks

- name: Triggering flatpak versions handler
  assert: { that: true, quiet: true }
  changed_when: true
  notify:
    - unmask flatpaks
    - update flatpak versions
  when: "'deploy' not in ansible_run_tags"