---
- name: Ensure flatpak ppa
  apt_repository:
    repo: ppa:alexlarsson/flatpak

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: safe

- name: Ensure flatpak package
  apt:
    name:
      - flatpak
      - gnome-software-plugin-flatpak
    state: latest
    install_recommends: yes

- name: Add the flathub flatpak repository remote to the system installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Register flatpak list
  set_fact:
    flatpak_list:
     - com.github.tchx84.Flatseal
     - io.freetubeapp.FreeTube
     - io.typora.Typora
     - com.teamspeak.TeamSpeak
     - net.codeindustry.MasterPDFEditor
     - com.github.Eloston.UngoogledChromium
     - com.github.xournalpp.xournalpp
     - com.belmoussaoui.Decoder
     - org.zotero.Zotero
     - info.mumble.Mumble
     - org.jitsi.jitsi-meet
     - com.github.jeromerobert.pdfarranger

- name: Install flatpak packages
  flatpak:
    remote: flathub
    name: "{{ item }}"
    state: present
  with_items: "{{ flatpak_list }}"

- name: Ensure flatpaks up-to-date
  shell: "flatpak update -y {{ item }}"
  become: yes
  with_items: "{{ flatpak_list }}"


