---
- name: Ensure masterpdf editor install script
  template:
    src: install_masterpdf.sh
    dest: "/srv/install_masterpdf.sh"
    mode: 0755

- name: Run masterpdf editor install script
  shell: /srv/install_masterpdf.sh
  args:
    chdir: /srv/
