---
- name: Ensure apt packages
  apt:
    name:
      - python3
      - python3-pip
      - gir1.2-poppler-0.18
      - libimage-exiftool-perl
    state: latest
    install_recommends: yes

- name: Ensure pip packages
  pip:
    name: "{{ item.name }}"
    executable: "{{ item.executable }}"
    state: "{{ item.state }}"
  become: true
  loop:
    - { name: "mat2", executable: "pip3", state: "latest"}
    - { name: "requests", executable: "pip3", state: "latest"}
    - { name: "virtualenv", executable: "pip3", state: "latest"}
    - { name: "git+https://github.com/tna76874/mdl.git", executable: "pip3", state: "latest"}
    - { name: "git+https://github.com/tna76874/vfs.git", executable: "pip3", state: "latest"}
    - { name: "git+https://github.com/tna76874/renamer.git", executable: "pip3", state: "latest"}
    - { name: "envelope", executable: "pip3", state: "latest"}
  ignore_errors: yes