---
- name: Ensure python3 and pip3
  apt:
    name:
      - python3
      - python3-pip
      - gir1.2-poppler-0.18
    state: latest
    install_recommends: yes

- name: Ensure pip packages
  pip:
    name: "{{ item.name }}"
    executable: "{{ item.executable }}"
    state: "{{ item.state }}"
  become: true
  loop:
    - { name: "mat2", executable: "pip3", state: "present"}