- name: Check if linux kernel is valid for portmaster
  set_fact:
    preflight_portmaster_kernel_valid: "{{ (ansible_kernel.split('.')[0] | int > 5) or ((ansible_kernel.split('.')[0] | int == 5) and (ansible_kernel.split('.')[1] | int >= 7)) }}"
    preflight_portmaster_deb_is_installed: False
    portmaster_install_status: "{{ portmaster_enabled|default(True)|bool }}"

- name: Debug message
  debug:
    msg: "{{ 'Valid kernel for portmaster' if preflight_portmaster_kernel_valid else 'Invalid kernel for portmaster' }}"
  when: portmaster_debug|default(False)

- name: Check installation status
  block:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Check if portmaster is installed
      set_fact:
        preflight_portmaster_deb_is_installed: "{{ 'portmaster' in ansible_facts.packages }}"

    - name: Debug message
      debug:
        msg: "{{ 'Portmaster is installied' if preflight_portmaster_deb_is_installed else 'Portmaster is not installied' }}"
      when: portmaster_debug|default(False)
  when: preflight_portmaster_kernel_valid

- name: Ensure initial portmaster script
  block:
    - apt:
        deb: "{{ portmaster_deb_url }}"
        state: present
      register: install_result

    - name: Install missing dependencies
      apt:
        name: "*"
        state: present
      when: install_result.failed

    - name: reload systemd
      systemd:
        daemon_reload: yes

  rescue:
    - name: Install missing dependencies
      apt:
        name: "*"
        state: present
  when: preflight_portmaster_deb_is_installed == False and preflight_portmaster_kernel_valid == True and portmaster_install_status == True

- name: Aktiviere und starte den Portmaster-Dienst
  systemd:
    name: portmaster
    enabled: yes
    state: started
  when: preflight_portmaster_deb_is_installed == False and preflight_portmaster_kernel_valid == True and portmaster_install_status == True

- name: Uninstall portmaster
  block:
    - name: Ensure portmaster package is absent
      apt:
        name: portmaster
        state: absent

    - name: reload systemd
      systemd:
        daemon_reload: yes
  when: preflight_portmaster_deb_is_installed == True and preflight_portmaster_kernel_valid == True and portmaster_install_status == False