---
- name: Ensure some snap packages
  snap:
    name:
      - mumble
      - pdftk
      - rambox
  ignore_errors: yes

- name: Ensure some classic snap packages
  snap:
    name:
      - code
    classic: yes
  ignore_errors: yes