---
- name: Ensure snap packages present
  snap:
    name:
      - pdftk
      - speedtest-cli
      - bing-wall
      - wonderwall
  ignore_errors: yes

- name: Ensure classic snap packages present
  snap:
    name:
      - restic
    classic: yes
  ignore_errors: yes

- name: Ensure snap packages absent
  snap:
    name:
      - code
      - rambox
      - firefox
      - chromium
      - snap-store
    state: absent
  ignore_errors: yes

- name: Ensure snaps are refreshed
  shell: "snap refresh"
  become: yes
  changed_when: false
  ignore_errors: yes
