---
- name: Ensure snap packages present
  snap:
    name:
      - pdftk
  ignore_errors: yes

- name: Ensure snap packages absent
  snap:
    name:
      - mumble
      - code
      - rambox
    state: absent
  ignore_errors: yes

- name: Ensure snaps are refreshed
  shell: "snap refresh"
  become: yes
