---
# extra roles
extra_roles_prefix: "hdhweg-extra-"
extra_roles_base_dir: "/root/.ansible/roles"
extra_roles: []
  # - repo: "git.server.xyz/user/repo.git"
  #   version: "master"
  #   name: "myrolename"
  #   user: "gituser"
  #   key: "gitapikey"