---
# source: https://docs.docker.com/engine/install/ubuntu/
- name: Ensure Prequisitions for Docker are met
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Ensure Docker Key is present
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Ensure Docker Repository is present
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Ensure Docker is installed
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    state: present

- name: Determine existing sudo users
  shell: 'grep sudo /etc/group | cut -d: -f4 | sed "s/,/\n/"'
  changed_when: false 
  register: sudo_users

- name: Ensure Users are in Docker group
  user:
    name: '{{ item }}'
    groups: docker
    append: yes
    state: present
  with_items: '{{ sudo_users.stdout_lines }}'

