---
- name: Determine existing users
  shell: 'cat /etc/passwd | grep /bin/bash | grep -v root | grep -v guest | cut -d: -f1'
  changed_when: false 
  register: ubuntu_users


- name: Ensure .wegrc integrated in .bashrc of existing users
  lineinfile:
    path: "/home/{{ item }}/.bashrc"
    regexp: '^source "(.*)/.wegrc"$'
    line: source "/home/{{ item }}/.wegrc"
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items: "{{ ubuntu_users.stdout_lines }}"

- name: Ensure .wegrc in homefolders
  template:
    src: "wegrc.j2"
    dest: "/home/{{ item }}/.wegrc"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0644
  with_items: "{{ ubuntu_users.stdout_lines }}"

- name: Ensure no update alias in bashrc of already present users
  lineinfile:
    path: "/home/{{ item }}/.bashrc"
    regexp: '^alias update=(.*)$'
    state: absent
  with_items: "{{ ubuntu_users.stdout_lines }}"

- name: Ensure .wegrc integrated in .bashrc of root user
  lineinfile:
    path: "/root/.bashrc"
    regexp: '^source "(.*)/.wegrc"$'
    line: source "/root/.wegrc"
    owner: root
    group: root

- name: Ensure .wegrc in root homefolder
  template:
    src: "wegrc.j2"
    dest: "/root/.wegrc"
    owner: root
    group: root
    mode: 0644

- name: Ensure .wegrc integrated in .bashrc of new create user
  lineinfile:
    path: "/etc/skel/.bashrc"
    regexp: '^source "(.*)/.wegrc"$'
    line: source "$HOME/.wegrc"

- name: Ensure .wegrc in skel folder
  template:
    src: "wegrc.j2"
    dest: "/etc/skel/.wegrc"
    owner: root
    group: root
    mode: 0644

- name: Ensure update alias in bashrc of new create user
  lineinfile:
    path: "/etc/skel/.bashrc"
    regexp: '^alias update=(.*)$'
    line: alias update="sudo git -C {{ config_repo_folder }} pull && sudo ansible-playbook {{ config_repo_folder }}/main.yml -t setup"

- name: Ensure update desktop entry
  template:
    src: update.desktop
    dest: "/home/{{ item }}/Schreibtisch/update.desktop"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0755
  with_items: "{{ ubuntu_users.stdout_lines }}"
  ignore_errors: yes

- name: Ensure trusted update launcher
  shell: dbus-launch gio set /home/{{ item }}/Schreibtisch/update.desktop "metadata::trusted" true
  become_user: "{{ item }}"
  with_items: "{{ ubuntu_users.stdout_lines }}"
  ignore_errors: yes
  changed_when: false

