---
- name: Add teamviewer key
  apt_key:
    url: https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc
    state: present

- name: Add teamviewer repository
  apt_repository:
    repo: deb http://linux.teamviewer.com/deb stable main
    state: present

- name: Ensure recoll ppa
  apt_repository:
    repo: ppa:recoll-backports/recoll-1.15-on

- name: Ensure veracrypt ppa
  apt_repository:
    repo: ppa:unit193/encryption

- name: Ensure xournal ppa
  apt_repository:
    repo: ppa:andreasbutti/xournalpp-master

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: safe

- name: Ensure packages
  apt:
    name:
      - byobu
      - zsh
      - curl
      - wget
      - dnsutils
      - git
      - sudo
      - htop
      - vim
      - nano
      - openssh-server
      - libreoffice
      - vlc
      - libxvidcore4
      - vlc-plugin-fluidsynth
      - vlc-plugin-jack
      - libdvdnav4
      - libdvdread4
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - ubuntu-restricted-extras
      - software-properties-common
      - audacious
      - audacious-plugins
      - xournalpp
      - poppler-utils
      - chromium-browser
      - chromium-browser
      - chromium-codecs-ffmpeg-extra
      - gimp
      - inkscape
      - gscan2pdf
      - ocrmypdf
      - tesseract-ocr
      - tesseract-ocr-deu
      - libfaac0
      - rclone
      - restic
      - clamav
      - clamav-freshclam
      - clamtk
      - gcc
      - wipe
      - unzip
      - p7zip
      - p7zip-full
      - p7zip-rar
      - tar
      - htop
      - screen
      - ncdu
      - dos2unix
      - speedtest-cli
      - imagemagick
      - teamviewer
      - gnuplot
      - gnuplot-x11
      - gnuplot-doc
      - recoll
      - poppler-utils
      - veracrypt
      - libgnome-keyring0
      - python3
      - python3-pip
    state: latest
    install_recommends: yes

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Update all dist packages to the latest version
  apt:
    upgrade: dist

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: disable TeamViewer daemon
  systemd:
    name: teamviewerd.service
    enabled: no
    state: stopped
  ignore_errors: yes

- name: running ansible playbook at reboot to make sure settings are as they should be
  cron:
    name: "running ansible playbook at reboot"
    special_time: reboot
    job: "(sleep 15m; cd /root/hdhweg-ubuntu; ansible-playbook main.yml > /dev/null 2>&1)&"
    user: root
    state: present

- import_tasks: firewall.yml

- import_tasks: alias.yml

- import_tasks: nautilus.yml
