---
- name: Add teamviewer key
  apt_key:
    url: https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc
    state: present

- name: Add teamviewer repository
  apt_repository:
    repo: deb http://linux.teamviewer.com/deb stable main
    state: present

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: safe

- name: Ensure packages
  apt:
    name:
      - byobu
      - zsh
      - curl
      - wget
      - dnsutils
      - git
      - sudo
      - htop
      - vim
      - nano
      - libreoffice
      - vlc
      - libxvidcore4
      - vlc-plugin-fluidsynth
      - vlc-plugin-jack
      - libdvdnav4
      - libdvdread4
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - ubuntu-restricted-extras
      - audacious
      - audacious-plugins
      - xournalpp
      - poppler-utils
      - chromium-browser
      - chromium-browser
      - chromium-codecs-ffmpeg-extra
      - gimp
      - inkscape
      - texstudio
      - gscan2pdf
      - ocrmypdf
      - tesseract-ocr
      - tesseract-ocr-deu
      - libfaac0
      - rclone
      - restic
      - clamav
      - clamav-freshclam
      - clamtk
      - gcc
      - wipe
      - unzip
      - p7zip
      - p7zip-full
      - p7zip-rar
      - htop
      - screen
      - ncdu
      - dos2unix
      - speedtest-cli
      - imagemagick
      - texlive-full
      - texlive-extra-utils
      - texlive-latex-recommended
      - teamviewer
    state: present

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Install mumble from snap
  snap:
    name:
      - mumble

- import_tasks: firewall.yml
