---
- name: disable TeamViewer daemon
  systemd:
    name: teamviewerd.service
    enabled: no
    state: stopped
  ignore_errors: yes
  when: ansible_facts['lsb']['id'] == "Ubuntu" and ansible_facts['lsb']['major_release']| int <= 20

- name: running ansible playbook at reboot to make sure settings are as they should be
  cron:
    name: "running ansible playbook at reboot"
    special_time: reboot
    job: "(sleep 15m; cd /root/hdhweg-ubuntu; ansible-playbook main.yml > /dev/null 2>&1)&"
    user: root
    state: present

- name: Ensure anaconda install script
  template:
    src: install_anaconda.sh
    dest: "/srv/install_anaconda.sh"
    mode: 0755

- name: Ensure update icon
  template:
    src: updateico.svg
    dest: "/usr/share/icons/breeze/apps/48/updateico.svg"
    mode: 0644

- name: Ensure update desktop entry
  template:
    src: update.desktop
    dest: "/usr/share/applications/update.desktop"
    mode: 0644
