---
- name: Include vars file if present
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - vars.yml
      skip: true

- name: disable TeamViewer daemon
  systemd:
    name: teamviewerd.service
    enabled: no
    state: stopped
  ignore_errors: yes
  when: ansible_facts['lsb']['id'] == "Ubuntu" and ansible_facts['lsb']['major_release']| int <= 20 and disable_teamviewer

- name: cleanup cron entry
  cron:
    name: "running ansible playbook at reboot"
    special_time: reboot
    job: "(sleep 15m; cd {{ config_repo_folder }}; ansible-playbook main.yml > /dev/null 2>&1)&"
    user: root
    state: absent

- name: Ensuring cron file - running base script 15min after reboot
  cron:
    name: "running ansible playbook at reboot"
    special_time: reboot
    job: "(sleep 15m; cd {{ config_repo_folder }}; ansible-playbook main.yml -t base > /dev/null 2>&1)&"
    user: root
    state: present
    cron_file: hdhweg_maintenance

- name: Ensure anaconda install script
  template:
    src: install_anaconda.sh
    dest: "/srv/install_anaconda.sh"
    mode: 0755

- name: Ensure update icon
  template:
    src: updateico.svg
    dest: "/usr/share/icons/updateico.svg"
    mode: 0644

- name: Ensure update desktop entry
  template:
    src: update.desktop
    dest: "/usr/share/applications/update.desktop"
    mode: 0644
