---
- name: disable TeamViewer daemon
  systemd:
    name: teamviewerd.service
    enabled: no
    state: stopped
  ignore_errors: yes

- name: running ansible playbook at reboot to make sure settings are as they should be
  cron:
    name: "running ansible playbook at reboot"
    special_time: reboot
    job: "(sleep 15m; cd /root/hdhweg-ubuntu; ansible-playbook main.yml > /dev/null 2>&1)&"
    user: root
    state: present

- name: Ensure masterpdf editor install script
  template:
    src: install_masterpdf.sh
    dest: "/srv/install_masterpdf.sh"
    mode: 0755

- name: Run masterpdf editor install script
  shell: /srv/install_masterpdf.sh
  args:
    chdir: /srv/

- name: Ensure teamspeak install script
  template:
    src: install_ts.sh
    dest: "/srv/install_ts.sh"
    mode: 0755
