---
- name: disable TeamViewer daemon
  systemd:
    name: teamviewerd.service
    enabled: no
    state: stopped
  ignore_errors: yes

- name: running ansible playbook at reboot to make sure settings are as they should be
  cron:
    name: "running ansible playbook at reboot"
    special_time: reboot
    job: "(sleep 15m; cd /root/hdhweg-ubuntu; ansible-playbook main.yml > /dev/null 2>&1)&"
    user: root
    state: present
