---
- name: Determine existing users
  shell: 'cat /etc/passwd | grep /bin/bash | grep -v root | cut -d: -f1'
  changed_when: false 
  register: ubuntu_users

- name: Ensure nautilus scripts directory
  file:
    path: "/home/{{ item }}/.local/share/nautilus/scripts"
    owner: "{{ item }}"
    state: directory
  with_items: "{{ ubuntu_users.stdout_lines }}"

- name: Ensure nautilus script to compress pdf documents
  template:
    src: "pdf_verkleinern"
    dest: "/home/{{ item }}/.local/share/nautilus/scripts/pdf_verkleinern"
    mode: 0755
  with_items: "{{ ubuntu_users.stdout_lines }}"

- name: Ensure nautilus script to merge pdf documents
  template:
    src: "pdf_zusammenfassen"
    dest: "/home/{{ item }}/.local/share/nautilus/scripts/pdf_zusammenfassen"
    mode: 0755
  with_items: "{{ ubuntu_users.stdout_lines }}"