---
- name: Ensure .wegrc integrated in .bashrc of root user
  lineinfile:
    path: "/root/.bashrc"
    regexp: '^source "(.*)/.wegrc"$'
    line: source "/root/.wegrc"
    owner: root
    group: root

- name: Ensure .wegrc in root homefolder
  template:
    src: "wegrc.j2"
    dest: "/root/.wegrc"
    owner: root
    group: root
    mode: 0644

- name: Ensure .wegrc integrated in .bashrc of new create user
  lineinfile:
    path: "/etc/skel/.bashrc"
    regexp: '^source "(.*)/.wegrc"$'
    line: source "$HOME/.wegrc"

- name: Ensure .wegrc in skel folder
  template:
    src: "wegrc.j2"
    dest: "/etc/skel/.wegrc"
    owner: root
    group: root
    mode: 0644

- name: Ensure update alias in bashrc of new create user
  lineinfile:
    path: "/etc/skel/.bashrc"
    regexp: '^alias update=(.*)$'
    line: alias update="sudo git -C {{ config_repo_folder }} pull && sudo ansible-playbook {{ config_repo_folder }}/main.yml -t setup"

- name: Ensure RustDesk root
  block:
    - name: Ensure directories
      file:
        path: "{{ item }}"
        owner: "root"
        state: directory
      loop:
        - "/root/.config/rustdesk/"

    - name: Ensure root RustDesk config
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
        owner: "root"
        group: "root"
      loop:
        - {src: "RustDesk2.toml.j2", dest: "/root/.config/rustdesk/RustDesk2.toml", mode: "0664"}
  ignore_errors: yes
  become: yes

- include_tasks: user_operations.yml
  loop: "{{ ubuntu_users.stdout_lines }}"
  loop_control:
    loop_var: user_item