---
- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: safe

- name: Ensure basic packages
  apt:
    name:
      - curl
      - chromium-browser
      - openssh-server
    state: latest

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Update all dist packages to the latest version
  apt:
    upgrade: dist

