#!/bin/bash
NAME=${1%.*}
QUAL="50"
THRES="85"

#Convert to jpeg
pdftoppm "$NAME".pdf ."$NAME"_o_ -jpeg
#Cut dark values
convert ."$NAME"_o_*.jpg -channel R,G,B -density 300 -quality "$QUAL" -white-threshold "$THRES"% ."$NAME"_g_%04d.jpg
#Convert back to pdf
pdfjam --a4paper ."$NAME"_g_*.jpg --outfile ."$NAME".pdf >/dev/null 2>&1
#Compress PDF #1
ps2pdf ."$NAME".pdf ."$NAME"_c.pdf
mv ."$NAME"_c.pdf ."$NAME".pdf
#Comporess PDF #2
gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH -sOutputFile=."$NAME"_c.pdf ."$NAME".pdf
mv ."$NAME"_c.pdf ."$NAME".pdf

#OCR of PDF
ocrmypdf ."$NAME".pdf "$NAME"_KLEIN.pdf >/dev/null 2>&1

# Delete working files
rm ."$NAME".pdf
rm ."$NAME"_g_*.jpg
rm ."$NAME"_o_*.jpg