#!/bin/bash
NAME=${1%.*}
QUAL="50"

function adjust_gray_level() {
    files=()
    while IFS= read -r -d '' file; do
        files+=("$file")
    done < <(find . -type f -iname "$NAME_o_*.jpg" -print0)

    for file in "${files[@]}"; do
        threshold=$(convert "$file" -colorspace gray -format "%[fx:mean]" info: | awk '{printf "%.0f\n", $1 * 100 * 0.75}')
        convert "$file" -colorspace Gray -density 300 -quality "$QUAL" -white-threshold "$threshold"% "$file"
    done
}

#Convert to jpeg
pdftoppm "$NAME".pdf ."$NAME"_o_ -jpeg

# remove dark parts of the image
adjust_gray_level

#Convert back to pdf
pdfjam --a4paper ."$NAME"_o_*.jpg --outfile ."$NAME".pdf >/dev/null 2>&1

#Compress PDF #1
ps2pdf ."$NAME".pdf ."$NAME"_c.pdf
mv ."$NAME"_c.pdf ."$NAME".pdf

#Compress PDF #2
gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH -sOutputFile=."$NAME"_c.pdf ."$NAME".pdf
mv ."$NAME"_c.pdf ."$NAME".pdf

#OCR of PDF
ocrmypdf ."$NAME".pdf "$NAME"_KLEIN.pdf >/dev/null 2>&1

# Delete working files
rm ."$NAME".pdf
rm ."$NAME"_o_*.jpg